name: 'Hello World'
description: 'Greet someone'
inputs:
  steamcmd-user-config:
    description: 'Base64 encoded SteamCMD user config'
    required: true
  environment:
    description: 'Environment to deploy to'
    required: true
runs:
  using: "composite"
  steps:
    - name: Check environment
      if: ${{ !contains(fromJSON('["prod", "playtest", "dev"]'), inputs.environment) }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed("Unknown environment: ${{ inputs.environment }}")

    - name: Install steamcmd
      shell: bash
      run: |
        sudo add-apt-repository multiverse
        sudo dpkg --add-architecture i386
        sudo apt update
        echo steam steam/question select "I AGREE" | sudo debconf-set-selections
        echo steam steam/license note '' | sudo debconf-set-selections
        sudo apt install steamcmd -y

    - name: Setup steamcmd
      shell: bash
      run: steamcmd +login anonymous +quit

    - name: Create user config
      run: base64 --decode <<< "$USER_CONFIG" > ~/Steam/config/config.vdf
      shell: bash
      env: 
        USER_CONFIG: ${{ inputs.steamcmd_user_config}}

    - name: Test steamcmd?
      shell: bash
      run: steamcmd +login NS2BDT +quit
