name: 'Version Check'
description: 'Check version has not been tagged on main'
runs:
  using: "composite"
  steps:
    - name: Get version
      id: get-version
      run: echo "version=$(jq -r .version build.json)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Checkout main
      uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: Get tags
      id: get-tags
      shell: bash
      run: |
        git fetch --all --tags --prune --prune-tags
        git pull
        echo "tag-output=$(git tag -l ${VERSION})" >> $GITHUB_OUTPUT

    - name: Check version isn't already tagged
      if: ${{ steps.get-version.outputs.version == steps.get-tags.output.tag-output }}
      uses: actions/github-script@v7
      with:
        script: |
          core.setFailed("Version ${steps.get-version.output.version} already exists")
