name: Main Push
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  # lint-lua:
  #   name: "Linter (Lua)"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "Linter installed"
  #         echo "linting happening!"

  # unittests-lua:
  #   name: Unit Tests (Lua)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "installed"
  #         echo "unittests happening!"

  version-check:
    name: Check Version
    # needs:
    #   - lint-lua
    #   - unittests-lua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/version-check'

  create-release:
    name: Create Release
    needs: version-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Tag commit
        run: |
          git tag $(jq -r .version build.json)
          git push --tags

      - name: Create Release Build
        run: |
          mkdir build
          cp build.json README.md build
          zip build.zip build

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --verify-tag --generate-notes $(jq -r .version build.json) 'build.zip#Test-Name-$(jq -r .version build.json)'

  deploy-dev:
    name: Deploy to Workshop (Dev)
    needs: version-check
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to dev
        uses: './.github/actions/deploy'
        with:
          steamcmd_user_config: ${{ secrets.USER_CONFIG }}
          environment: dev

  deploy-playtest:
    name: Deploy to Workshop (Playtest)
    needs: version-check
    runs-on: ubuntu-latest
    environment: playtest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to dev
        uses: './.github/actions/deploy'
        with:
          steamcmd_user_config: ${{ secrets.USER_CONFIG }}
          environment: dev

  deploy-prod:
    name: Deploy to Workshop (Playtest)
    needs: version-check
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to dev
        uses: './.github/actions/deploy'
        with:
          steamcmd_user_config: ${{ secrets.USER_CONFIG }}
          environment: dev
