name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  lint-lua:
    name: "Linter (Lua)"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Linter installed"
          echo "linting happening!"

  unittests-lua:
    name: Unit Tests (Lua)
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "installed"
          echo "unittests happening!"

  version-check:
    name: Check Version
    needs:
      - lint-lua
      - unittests-lua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/version-check'

  create-release:
    name: Create Release
    needs: version-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Tag commit
        run: |
          git tag $(jq -r .version build.json)
          git push --tags
      - name: Create Release Build
        run: |
          mkdir build
          cp build.json README.md build
          zip build.zip build
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --verify-tag --generate-notes $(jq -r .version build.json) 'build.zip#Test Name'

  Explore-GitHub-Actions:
    name: Deploy to Workshop
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: test
        run: |
          pwd
          ls -lah
          cat build.json
      - name: Install steamcmd
        run: |
          sudo add-apt-repository multiverse
          sudo dpkg --add-architecture i386
          sudo apt update
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note '' | sudo debconf-set-selections
          sudo apt install steamcmd -y
      - name: Setup steamcmd
        run: |
          steamcmd +login anonymous +quit
      - name: Create user config
        env:
          USER_CONFIG: ${{ secrets.USER_CONFIG}}
        run: |
          base64 --decode <<< "$USER_CONFIG" > ~/Steam/config/config.vdf
      - name: Test steamcmd?
        run: |
          steamcmd +login NS2BDT +quit
